version: '3'

services:
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    command: ["--max-timeout", "3600"]
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: scrapy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
